Tag to node routes
bytecraftoy/aalto-project-2021 pull request #140
Opened 2022-04-18 08:40 UTC by tobifalowo

Change the server-side routes to later enable tagging nodes

2022-04-21 15:25 UTC, 10hoe approved these changes
LGTM

2022-04-25 07:04 UTC, jgke requested changes

2022-04-25 07:04 UTC, jgke commented on src/server/route/path.ts
> -            methods: ['GET'],
The API should be:
- Get tags for project: GET /tag/:proj
— this should return both tags and the tag-node relations
- Add tag to node: POST /tag/:proj/:node
- Delete tag from node: DELETE /tag/:proj/:node/:tag
Don’t include separate endpoints for creating a tag and adding one, instead do it based on the request — no tagId -> create new label, yes tagId -> use that.

2022-04-25 07:04 UTC, jgke commented on src/server/route/routes/tag.ts
> +    const tagColor = req.body.tagColor;
check permissions

2022-04-25 07:04 UTC, jgke commented on src/server/route/routes/tag.ts
> +
Check permissions

2022-04-25 07:04 UTC, jgke commented on src/server/route/path.ts
> -            methods: ['GET'],
Also, add api doc annotations.

2022-05-10 06:11 UTC, merged