add kurkku mopo
bytecraftoy/aalto-project-2021 pull request #4
Opened 2021-11-09 17:10 UTC by rendurok

2021-11-11 09:01 UTC, jaakkoha-bytecraft requested changes

2021-11-11 09:01 UTC, jaakkoha-bytecraft commented on src/client/Components/app.tsx
>              <div>
Tässä voisi vaihtaa inputText-muuttujanimen `inputPlaceholder` tjsp.

2021-11-12 09:26 UTC, rendurok commented on src/client/Components/app.tsx
>              <div>
muuttujan nimi vaihdettu

2021-11-12 10:29 UTC, jaakkoha-bytecraft approved these changes

2021-11-15 11:23 UTC, merged