no-console lint rule added. Removed logs from Graph.tsx
bytecraftoy/aalto-project-2021 pull request #79
Opened 2022-03-14 14:51 UTC by WatMan77

2022-03-14 14:58 UTC, rendurok commented
Cypress auto-fails because of linter warnings. Maybe fix the rest of the 'console.log's too?

2022-03-14 18:08 UTC, rendurok requested changes
linter still warns about 2 lines, these should probably be fixed

2022-03-14 20:36 UTC, rendurok approved these changes

2022-03-15 21:37 UTC, jgke approved these changes

2022-03-16 13:30 UTC, merged