add rudimentaty ui for assigning users
bytecraftoy/aalto-project-2021 pull request #94
Opened 2022-03-21 20:00 UTC by rendurok

2022-03-22 21:51 UTC, Gnirps00 requested changes
näyttää tosi hyvältä, mut tuli helppoja lint warningii, voit korjata ne, niin ok

2022-03-23 11:25 UTC, rendurok commented
ne ei liity tähän ominaisuuteen mitenkään, niin ei kuulu tähän pulliin niitten fixaaminen

2022-03-23 11:56 UTC, Gnirps00 approved these changes
Nyt toimii ilman warningeja, nice

2022-03-23 14:17 UTC, jaakkoha-bytecraft approved these changes

2022-03-23 14:17 UTC, merged